version: "3"
services:
  node:
    image: node:latest
    volumes: 
      - ./:/app
    working_dir: /app
    ports:
      - ${CLIENT_PORT}:3000 
      - ${PORT}:5000  
    depends_on:
      - database
    command: sh -c "npm rebuild node-sass && npm start"
    environment:
      SQL_HOST: database
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ".env"
    ports:
      - ${SQL_PORTDOCKER}:3306
    environment: 
      MYSQL_DATABASE: ${SQL_DB}
      MYSQL_USER: ${SQL_USER}
      MYSQL_ROOT_PASSWORD: ${SQL_PASSWORD}     
      SQL_HOST: ${SQL_HOSTDOCKER}
    volumes:
      - ./mysql-data:/var/lib/mysql