export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const HANDLE_SIGNUP_CHANGE = 'HANDLE_SIGNUP_CHANGE'
export const HANDLE_LOGIN_CHANGE = 'HANDLE_LOGIN_CHANGE'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'

export const HANDLE_SUBMIT = 'HANDLE_SUBMIT'
export const HANDLE_FORM_SUBMIT = 'HANDLE_FORM_SUBMIT'

export const LOGOUT_USER = 'LOGOUT_USER'

export const GET_ALL_DRAWINGS = 'GET_ALL_DRAWINGS'
export const GET_ONE_DRAWING = 'GET_ONE_DRAWING'
export const HANDLE_DRAWING_CHANGE = 'HANDLE_DRAWING_CHANGE'

export const HANDLE_FILE_UPLOAD = 'HANDLE_FILE_UPLOAD'


export const ALL_DRAWINGS = 'ALL_DRAWINGS'
export const ALL_PERSONAL_DRAWINGS = 'ALL_PERSONAL_DRAWINGS'
export const ALL_LISTINGS = 'ALL_LISTINGS' 

export const HANDLE_LISTING_CHANGE = 'HANDLE_LISTING_CHANGE'
export const HANDLE_LISTING_SUBMIT = 'HANDLE_LISTING_SUBMIT'

export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'